// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m AddPlayerBuff) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.PlayerID)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint16(m.Buff)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt32(m.Time)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *AddPlayerBuff) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.PlayerID = tmp
	}
	{
		tmp, err := cur.ReadUint16()
		if err != nil {
			return err
		}
		m.Buff = tmp
	}
	{
		tmp, err := cur.ReadInt32()
		if err != nil {
			return err
		}
		m.Time = tmp
	}
	return nil
}
