// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m AnglerQuest) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.Quest)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteBool(m.Completed)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *AnglerQuest) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Quest = tmp
	}
	{
		tmp, err := cur.ReadBool()
		if err != nil {
			return err
		}
		m.Completed = tmp
	}
	return nil
}
