// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m ClientUUID) Append(cur *cursor.Cursor) (err error) {
	{
		_, err := cur.WriteString(m.UUID)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *ClientUUID) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadString()
		if err != nil {
			return err
		}
		m.UUID = tmp
	}
	return nil
}
