// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m ClientFinishedInventoryChangesOnThisTick) Append(cur *cursor.Cursor) (err error) {
	return nil
}
func (m *ClientFinishedInventoryChangesOnThisTick) Scan(cur *cursor.Cursor) (err error) {
	return nil
}
