// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m CrystalInvasionSendWaitTime) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteInt32(m.TimeUntilNextWave)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *CrystalInvasionSendWaitTime) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadInt32()
		if err != nil {
			return err
		}
		m.TimeUntilNextWave = tmp
	}
	return nil
}
