// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m DestroyProjectile) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteInt16(m.ProjectileID)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.Owner)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *DestroyProjectile) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.ProjectileID = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Owner = tmp
	}
	return nil
}
