// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m Disconnect) Append(cur *cursor.Cursor) (err error) {
	{
		err := m.Reason.Append(cur)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *Disconnect) Scan(cur *cursor.Cursor) (err error) {
	{
		err := m.Reason.Scan(cur)
		if err != nil {
			return err
		}
	}
	return nil
}
