// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m Emoji) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.PlayerIndex)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.EmoticonID)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *Emoji) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.PlayerIndex = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.EmoticonID = tmp
	}
	return nil
}
