// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m FoodPlatterTryPlacing) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteInt16(m.X)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.Y)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.ItemID)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.Prefix)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.Stack)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *FoodPlatterTryPlacing) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.X = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.Y = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.ItemID = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Prefix = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.Stack = tmp
	}
	return nil
}
