// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m ForceItemIntoNearestChest) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.InventorySlot)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *ForceItemIntoNearestChest) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.InventorySlot = tmp
	}
	return nil
}
