// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m GrowFX) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.EffectFlags)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt32(m.X)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt32(m.Y)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.Data)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.TreeGore)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *GrowFX) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.EffectFlags = tmp
	}
	{
		tmp, err := cur.ReadInt32()
		if err != nil {
			return err
		}
		m.X = tmp
	}
	{
		tmp, err := cur.ReadInt32()
		if err != nil {
			return err
		}
		m.Y = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Data = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.TreeGore = tmp
	}
	return nil
}
