// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m LandGolfBallInCup) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.PlayerID)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint16(m.X)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint16(m.Y)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint16(m.NumberofHits)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint16(m.ProjID)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *LandGolfBallInCup) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.PlayerID = tmp
	}
	{
		tmp, err := cur.ReadUint16()
		if err != nil {
			return err
		}
		m.X = tmp
	}
	{
		tmp, err := cur.ReadUint16()
		if err != nil {
			return err
		}
		m.Y = tmp
	}
	{
		tmp, err := cur.ReadUint16()
		if err != nil {
			return err
		}
		m.NumberofHits = tmp
	}
	{
		tmp, err := cur.ReadUint16()
		if err != nil {
			return err
		}
		m.ProjID = tmp
	}
	return nil
}
