// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m LoadNetModule) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint16(m.ModuleID)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *LoadNetModule) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint16()
		if err != nil {
			return err
		}
		m.ModuleID = tmp
	}
	return nil
}
