// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m MoonLordCountdown) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteInt32(m.MoonLordCountdown)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *MoonLordCountdown) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadInt32()
		if err != nil {
			return err
		}
		m.MoonLordCountdown = tmp
	}
	return nil
}
