// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m NebulaLevelUp) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.PlayerID)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint16(m.LevelUpType)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteFloat32(m.OriginX)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteFloat32(m.OriginY)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *NebulaLevelUp) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.PlayerID = tmp
	}
	{
		tmp, err := cur.ReadUint16()
		if err != nil {
			return err
		}
		m.LevelUpType = tmp
	}
	{
		tmp, err := cur.ReadFloat32()
		if err != nil {
			return err
		}
		m.OriginX = tmp
	}
	{
		tmp, err := cur.ReadFloat32()
		if err != nil {
			return err
		}
		m.OriginY = tmp
	}
	return nil
}
