// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m NPCHomeUpdate) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteInt16(m.NPCID)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.HomeTileX)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.HomeTileY)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.Homeless)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *NPCHomeUpdate) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.NPCID = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.HomeTileX = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.HomeTileY = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Homeless = tmp
	}
	return nil
}
