// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m NPCStrike) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteInt16(m.NPCID)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.Damage)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteFloat32(m.Knockback)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.HitDirection)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteBool(m.Crit)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *NPCStrike) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.NPCID = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.Damage = tmp
	}
	{
		tmp, err := cur.ReadFloat32()
		if err != nil {
			return err
		}
		m.Knockback = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.HitDirection = tmp
	}
	{
		tmp, err := cur.ReadBool()
		if err != nil {
			return err
		}
		m.Crit = tmp
	}
	return nil
}
