// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m NPCShopItem) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.Slot)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.ItemType)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.Stack)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.Prefix)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt32(m.Value)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.Flags)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *NPCShopItem) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Slot = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.ItemType = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.Stack = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Prefix = tmp
	}
	{
		tmp, err := cur.ReadInt32()
		if err != nil {
			return err
		}
		m.Value = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Flags = tmp
	}
	return nil
}
