// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m Null) Append(cur *cursor.Cursor) (err error) {
	return nil
}
func (m *Null) Scan(cur *cursor.Cursor) (err error) {
	return nil
}
