// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m OpenChest) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteInt16(m.TileX)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.TileY)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *OpenChest) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.TileX = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.TileY = tmp
	}
	return nil
}
