// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m PlaceChest) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.Action)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.TileX)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.TileY)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.Style)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.ChestIDtodestroy)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *PlaceChest) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Action = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.TileX = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.TileY = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.Style = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.ChestIDtodestroy = tmp
	}
	return nil
}
