// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m PlayerInventorySlot) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.PlayerID)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.SlotID)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.Stack)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.Prefix)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.ItemNetID)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *PlayerInventorySlot) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.PlayerID = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.SlotID = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.Stack = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Prefix = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.ItemNetID = tmp
	}
	return nil
}
