// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m PlayerZone) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.PlayerID)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.ZoneFlags1)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.ZoneFlags2)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.ZoneFlags3)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.ZoneFlags4)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *PlayerZone) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.PlayerID = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.ZoneFlags1 = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.ZoneFlags2 = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.ZoneFlags3 = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.ZoneFlags4 = tmp
	}
	return nil
}
