// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m PlayLegacySound) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteFloat32(m.X)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteFloat32(m.Y)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint16(m.SoundID)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.SoundFlags)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *PlayLegacySound) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadFloat32()
		if err != nil {
			return err
		}
		m.X = tmp
	}
	{
		tmp, err := cur.ReadFloat32()
		if err != nil {
			return err
		}
		m.Y = tmp
	}
	{
		tmp, err := cur.ReadUint16()
		if err != nil {
			return err
		}
		m.SoundID = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.SoundFlags = tmp
	}
	return nil
}
