// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m PlayerHurtV2) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.PlayerID)
		if err != nil {
			return err
		}
	}
	{
		err := m.PlayerDeathReason.Append(cur)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.Damage)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.HitDirection)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.Flags)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt8(m.CooldownCounter)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *PlayerHurtV2) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.PlayerID = tmp
	}
	{
		err := m.PlayerDeathReason.Scan(cur)
		if err != nil {
			return err
		}
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.Damage = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.HitDirection = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Flags = tmp
	}
	{
		tmp, err := cur.ReadInt8()
		if err != nil {
			return err
		}
		m.CooldownCounter = tmp
	}
	return nil
}
