// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m PlayerInfo) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.PlayerID)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.SkinVarient)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.Hair)
		if err != nil {
			return err
		}
	}
	{
		_, err := cur.WriteString(m.Name)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.HairDye)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.HideVisuals)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.HideVisuals2)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.HideMisc)
		if err != nil {
			return err
		}
	}
	{
		err := m.HairColor.Append(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.SkinColor.Append(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.EyeColor.Append(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.ShirtColor.Append(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.UnderShirtColor.Append(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.PantsColor.Append(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.ShoeColor.Append(cur)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.DifficultyFlags)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.TorchFlags)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *PlayerInfo) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.PlayerID = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.SkinVarient = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Hair = tmp
	}
	{
		tmp, err := cur.ReadString()
		if err != nil {
			return err
		}
		m.Name = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.HairDye = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.HideVisuals = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.HideVisuals2 = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.HideMisc = tmp
	}
	{
		err := m.HairColor.Scan(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.SkinColor.Scan(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.EyeColor.Scan(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.ShirtColor.Scan(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.UnderShirtColor.Scan(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.PantsColor.Scan(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.ShoeColor.Scan(cur)
		if err != nil {
			return err
		}
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.DifficultyFlags = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.TorchFlags = tmp
	}
	return nil
}
