// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m PoofofSmoke) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint32(m.PackedVector)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *PoofofSmoke) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint32()
		if err != nil {
			return err
		}
		m.PackedVector = tmp
	}
	return nil
}
