// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m ReleaseNPC) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteInt32(m.X)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt32(m.Y)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.NPCType)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.Style)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *ReleaseNPC) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadInt32()
		if err != nil {
			return err
		}
		m.X = tmp
	}
	{
		tmp, err := cur.ReadInt32()
		if err != nil {
			return err
		}
		m.Y = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.NPCType = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Style = tmp
	}
	return nil
}
