// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m RemoveItemOwner) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteInt16(m.ItemIndex)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *RemoveItemOwner) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.ItemIndex = tmp
	}
	return nil
}
