// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m ReportInvasionProgress) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteInt32(m.Progress)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt32(m.MaxProgress)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt8(m.Icon)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt8(m.Wave)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *ReportInvasionProgress) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadInt32()
		if err != nil {
			return err
		}
		m.Progress = tmp
	}
	{
		tmp, err := cur.ReadInt32()
		if err != nil {
			return err
		}
		m.MaxProgress = tmp
	}
	{
		tmp, err := cur.ReadInt8()
		if err != nil {
			return err
		}
		m.Icon = tmp
	}
	{
		tmp, err := cur.ReadInt8()
		if err != nil {
			return err
		}
		m.Wave = tmp
	}
	return nil
}
