// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m SectionTileFrame) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteInt16(m.StartX)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.StartY)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.EndX)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.EndY)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *SectionTileFrame) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.StartX = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.StartY = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.EndX = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.EndY = tmp
	}
	return nil
}
