// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m SetPlayerStealth) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.Player)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteFloat32(m.Stealth)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *SetPlayerStealth) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Player = tmp
	}
	{
		tmp, err := cur.ReadFloat32()
		if err != nil {
			return err
		}
		m.Stealth = tmp
	}
	return nil
}
