// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m SmartTextMessage) Append(cur *cursor.Cursor) (err error) {
	{
		err := m.MessageColor.Append(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.Message.Append(cur)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.MessageLength)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *SmartTextMessage) Scan(cur *cursor.Cursor) (err error) {
	{
		err := m.MessageColor.Scan(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.Message.Scan(cur)
		if err != nil {
			return err
		}
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.MessageLength = tmp
	}
	return nil
}
