// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m SpawnBossInvasion) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteInt16(m.PlayerID)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.Type)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *SpawnBossInvasion) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.PlayerID = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.Type = tmp
	}
	return nil
}
