// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m Status) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteInt32(m.StatusMax)
		if err != nil {
			return err
		}
	}
	{
		err := m.StatusText.Append(cur)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.StatusTextFlags)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *Status) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadInt32()
		if err != nil {
			return err
		}
		m.StatusMax = tmp
	}
	{
		err := m.StatusText.Scan(cur)
		if err != nil {
			return err
		}
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.StatusTextFlags = tmp
	}
	return nil
}
