// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m SyncPlayerChestIndex) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.Player)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.Chest)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *SyncPlayerChestIndex) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Player = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.Chest = tmp
	}
	return nil
}
