// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m SyncCavernMonsterType) Append(cur *cursor.Cursor) (err error) {
	{
		for _, v := range m {
			{
				err := cur.WriteUint16(v)
				if err != nil {
					return err
				}
			}
		}
	}
	return nil
}
func (m *SyncCavernMonsterType) Scan(cur *cursor.Cursor) (err error) {
	{
		n := 6
		for i := 0; i < int(n); i++ {
			{
				tmp, err := cur.ReadUint16()
				if err != nil {
					return err
				}
				m[i] = tmp
			}
		}
	}
	return nil
}
