// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m TravellingMerchantInventory) Append(cur *cursor.Cursor) (err error) {
	{
		for _, v := range m.Items {
			{
				err := cur.WriteInt16(v)
				if err != nil {
					return err
				}
			}
		}
	}
	return nil
}
func (m *TravellingMerchantInventory) Scan(cur *cursor.Cursor) (err error) {
	{
		n := 40
		for i := 0; i < int(n); i++ {
			{
				tmp, err := cur.ReadInt16()
				if err != nil {
					return err
				}
				m.Items[i] = tmp
			}
		}
	}
	return nil
}
