// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m UpdatePlayerLuckFactors) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.PlayerID)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt32(m.LadybugLuckTimeRemaining)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteFloat32(m.TorchLuck)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.LuckPotion)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteBool(m.HasGardenGnomeNearby)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *UpdatePlayerLuckFactors) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.PlayerID = tmp
	}
	{
		tmp, err := cur.ReadInt32()
		if err != nil {
			return err
		}
		m.LadybugLuckTimeRemaining = tmp
	}
	{
		tmp, err := cur.ReadFloat32()
		if err != nil {
			return err
		}
		m.TorchLuck = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.LuckPotion = tmp
	}
	{
		tmp, err := cur.ReadBool()
		if err != nil {
			return err
		}
		m.HasGardenGnomeNearby = tmp
	}
	return nil
}
