// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m UpdateShieldStrengths) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint16(m.SolarTowerShieldStrength)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint16(m.VortexTowerShieldStrength)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint16(m.NebulaTowerShieldStrength)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint16(m.StardustTowerShieldStrength)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *UpdateShieldStrengths) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint16()
		if err != nil {
			return err
		}
		m.SolarTowerShieldStrength = tmp
	}
	{
		tmp, err := cur.ReadUint16()
		if err != nil {
			return err
		}
		m.VortexTowerShieldStrength = tmp
	}
	{
		tmp, err := cur.ReadUint16()
		if err != nil {
			return err
		}
		m.NebulaTowerShieldStrength = tmp
	}
	{
		tmp, err := cur.ReadUint16()
		if err != nil {
			return err
		}
		m.StardustTowerShieldStrength = tmp
	}
	return nil
}
