// Code generated by gomacro; DO NOT EDIT.
package messages

import "github.com/tdakkota/cursor"

func (m UpdateNPCName) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteInt16(m.NPCID)
		if err != nil {
			return err
		}
	}
	{
		_, err := cur.WriteString(m.Name)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt32(m.TownNpcVariationIndex)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *UpdateNPCName) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.NPCID = tmp
	}
	{
		tmp, err := cur.ReadString()
		if err != nil {
			return err
		}
		m.Name = tmp
	}
	{
		tmp, err := cur.ReadInt32()
		if err != nil {
			return err
		}
		m.TownNpcVariationIndex = tmp
	}
	return nil
}
