// Code generated by gomacro; DO NOT EDIT.
package tile

import "github.com/tdakkota/cursor"

func (m DisplayDoll) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.DollFlags1)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.DollFlags2)
		if err != nil {
			return err
		}
	}
	{
		err := m.Item.Append(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.Dye.Append(cur)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *DisplayDoll) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.DollFlags1 = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.DollFlags2 = tmp
	}
	{
		err := m.Item.Scan(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.Dye.Scan(cur)
		if err != nil {
			return err
		}
	}
	return nil
}
