// Code generated by gomacro; DO NOT EDIT.
package tile

import "github.com/tdakkota/cursor"

func (m Dye) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteInt16(m.DyeType)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.DyePrefix)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.DyeStack)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *Dye) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.DyeType = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.DyePrefix = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.DyeStack = tmp
	}
	return nil
}
