// Code generated by gomacro; DO NOT EDIT.
package tile

import "github.com/tdakkota/cursor"

func (m Empty) Append(cur *cursor.Cursor) (err error) {
	return nil
}
func (m *Empty) Scan(cur *cursor.Cursor) (err error) {
	return nil
}
