// Code generated by gomacro; DO NOT EDIT.
package tile

import "github.com/tdakkota/cursor"

func (m HatRack) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.HatFlags)
		if err != nil {
			return err
		}
	}
	{
		err := m.Item.Append(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.Dye.Append(cur)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *HatRack) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.HatFlags = tmp
	}
	{
		err := m.Item.Scan(cur)
		if err != nil {
			return err
		}
	}
	{
		err := m.Dye.Scan(cur)
		if err != nil {
			return err
		}
	}
	return nil
}
