// Code generated by gomacro; DO NOT EDIT.
package tile

import "github.com/tdakkota/cursor"

func (m Item) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteInt16(m.ItemType)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.ItemPrefix)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.ItemStack)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *Item) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.ItemType = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.ItemPrefix = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.ItemStack = tmp
	}
	return nil
}
