// Code generated by gomacro; DO NOT EDIT.
package tile

import "github.com/tdakkota/cursor"

func (m LogicSensor) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.LogicCheckType)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteBool(m.On)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *LogicSensor) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.LogicCheckType = tmp
	}
	{
		tmp, err := cur.ReadBool()
		if err != nil {
			return err
		}
		m.On = tmp
	}
	return nil
}
