// Code generated by gomacro; DO NOT EDIT.
package tile

import "github.com/tdakkota/cursor"

func (m TrainingDummy) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteInt16(m.NPCIndex)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *TrainingDummy) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.NPCIndex = tmp
	}
	return nil
}
