// Code generated by gomacro; DO NOT EDIT.
package tile

import "github.com/tdakkota/cursor"

func (m WeaponsRack) Append(cur *cursor.Cursor) (err error) {
	{
		err := m.Item.Append(cur)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *WeaponsRack) Scan(cur *cursor.Cursor) (err error) {
	{
		err := m.Item.Scan(cur)
		if err != nil {
			return err
		}
	}
	return nil
}
