// Code generated by gomacro; DO NOT EDIT.
package structs

import "github.com/tdakkota/cursor"

func (m Color) Append(cur *cursor.Cursor) (err error) {
	{
		err := cur.WriteUint8(m.Red)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.Green)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteUint8(m.Blue)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *Color) Scan(cur *cursor.Cursor) (err error) {
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Red = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Green = tmp
	}
	{
		tmp, err := cur.ReadUint8()
		if err != nil {
			return err
		}
		m.Blue = tmp
	}
	return nil
}
