// Code generated by gomacro; DO NOT EDIT.
package structs

import "github.com/tdakkota/cursor"

func (m TileEntity) Append(cur *cursor.Cursor) (err error) {
	{
		err := m.Type.Append(cur)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt32(m.ID)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.X)
		if err != nil {
			return err
		}
	}
	{
		err := cur.WriteInt16(m.Y)
		if err != nil {
			return err
		}
	}
	{
		err := m.ExtraData.Append(cur)
		if err != nil {
			return err
		}
	}
	return nil
}
func (m *TileEntity) Scan(cur *cursor.Cursor) (err error) {
	{
		err := m.Type.Scan(cur)
		if err != nil {
			return err
		}
	}
	{
		tmp, err := cur.ReadInt32()
		if err != nil {
			return err
		}
		m.ID = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.X = tmp
	}
	{
		tmp, err := cur.ReadInt16()
		if err != nil {
			return err
		}
		m.Y = tmp
	}
	{
		err := m.ExtraData.Scan(cur)
		if err != nil {
			return err
		}
	}
	return nil
}
